### ISSUE TITLE
Width and Height 

### ISSUE THREAD

**Issue by ghost** [kartsims/easysvg#1]
Hello

I've read on the stackoverflow-page that you want to know what features you could integrate into this nice  project. I would say that the most needed feature would be a bounding box like the GD Lib offers for Fonts, so I know how big of a box my String will generate at the given Fontsize and with a given font. Also: Linebreak :)

Best wishes
Mortimer

**Comment by kartsims** [comment]
Hey Mortimer,

Some guy asked me three weeks ago the same thing about linebreaks so I will surely implement this feature very soon. I am glad to hear from people using my lib :)

Thanks for the message, best wishes to you too

Simon

**Comment by kartsims** [comment]
Just to let you know the code has been updated ;-)

**Comment by ghost** [comment]
Wow, that was amazingly quick. Well, next on your list should be inserting other SVG, as of then, I would ditch my phpSVG Lib and use yours :D
I like this Repository!

**Comment by kartsims** [comment]
Hehe, just happy to help :)

What do you mean by inserting other SVG ?... Could you send me a use case ?

**Comment by ghost** [comment]
For Example:
phpSVG (https://code.google.com/p/phpsvg/) has in its examples a merger that allowes to merge two SVG to a single SVG (demo: http://mortimerneuss.de/test/phpsvg/example/merge.svg.php)

I currently use phpSVG to combine a Font and a SVG and receive a single (merged) SVG. What your lib currently is doing (as far as I digged into it) is creating a font (nice) but is not supporting injecting another SVG (like a small Logo or something). Do you think that this would be hard?

**Comment by ghost** [comment]
The good thing about phpSVG is that you can give it a SVG as a stage instance and then add another SVG or Text to it. This way I can make SVG templates in the correct size and then just add text to it. The bad thing: No custom Fonts :/

Look here: http://mortimerneuss.de/test/phpsvg/example/text.php
Code: http://mortimerneuss.de/test/phpsvg/example/text.txt
template svg: http://mortimerneuss.de/test/phpsvg/example/resource/simple_label.svg

Currently, I'm already happy that I could use your easySVG Lib to create a custom Font SVG (now even knowing the width and height!) and I would now just add the SVG from easySVG to the template SVG with phpSVG. This way I can have custom Fonts on my template svg. Even more awesome would it be if I could ditch the phpSVG comepletely and have easySVG make all this... u know? :D

Mortimer

**Comment by kartsims** [comment]
Hmm I see what you mean there but that is not really the purpose of easysvg...

However you can still achieve this without phpSVG by extracting the definition(s) or/and path(s) and proceeding like this :

$svg = new EasySVG();

// here create your text
// ...

// add the other SVG's definition or path with any attributes
$svg->addPath($def, $attributes);

// then output the SVG
echo $svg->asXML();

This means you need to extract the definition(s) you want to insert in the SVG. It is just another way of doing it.

As I open your sample SVG, I see that you use different tags (not path) so you can't extract definitions... So I see your point and will look into it soon :)

Thanks for the feedback!

++

Simon
