### ISSUE TITLE
license of font file

### ISSUE THREAD

**Issue by splitbrain** [kartsims/easysvg#10]
I'm wondering about the license of the included font file. I only found this website: https://www.fonts.com/font/la-goupil/paris/bold - it seems the font is non-free?

**Comment by kartsims** [comment]
Oh gosh you are right

This was originally done for a professionnal project where the font was paid for... I should remove it and use a free one in the demo, thanks for noticing that

**Comment by kartsims** [comment]
Updated, thanks again for the input 👍
