### ISSUE TITLE
How can placed svg x and y to 0

### ISSUE THREAD

**Issue by s-meiser** [kartsims/easysvg#13]
It is possible to placed the svg horizontal und vertical to zero? When yes, how?

```
-----------------
|This IS A TEXT
|
```
The Box of "This IS A TEXT" should to zero of x and y positition.

Greetings
Sebastian

**Comment by kartsims** [comment]
This is the default behavior.

This might come from your font, some font have "spaces" included...

Consider this example (from [FontForge homepage](https://fontforge.github.io/en-US/))

![FontForge homepage](https://fontforge.github.io/assets/img/hero.png)

The top line is the base where the font is placed. Depending on your font it can include some sort of padding...
