### ISSUE TITLE
resize

### ISSUE THREAD

**Issue by bnkcrypt** [kartsims/easysvg#19]
I have noticed that when resize the svg displayed on webpage with css height weight defined it does not reduced the svg display size but show half part of it instead ( shows partial svg )  . Is there something can be done to output

**Comment by kartsims** [comment]
It is probably an issue with the SVG itself. Can you please provide an example ?

**Comment by ricardoboss** [comment]
@bnkcrypt is this still an issue? Otherwise, I'd like to close it.

**Comment by kartsims** [comment]
it's 4 years old, probably safe to close!, thanks for looking into it @ricardoboss
