### ISSUE TITLE
Tag a (stable) version

### ISSUE THREAD

**Issue by MatthiasKuehneEllerhold** [kartsims/easysvg#24]
We'd like to use your libary and it would greatly help us if you could tag a (stable) version.

**Comment by kartsims** [comment]
How am I supposed to do that ? on Github you mean or somewhere else ?

**Comment by MatthiasKuehneEllerhold** [comment]
A normal git tag would be nice
```
git tag <version number>
git push --tags
```

**Comment by kartsims** [comment]
[Done](https://github.com/kartsims/easysvg/releases/tag/stable)

I have tagged the current `master` as `stable`. No changes are to be made anytime soon but feel free to track this tag.

**Comment by MatthiasKuehneEllerhold** [comment]
I thought more of a numeric tag like "1.0"... but thats fine.

**Comment by MatthiasKuehneEllerhold** [comment]
Actually composer doesnt like "stable" as a version.
```
  [UnexpectedValueException]                                                  
  Could not parse version constraint stable: Invalid version string "stable"  
```

Could you please use a numeric version like 1.0 or something similar?

**Comment by MatthiasKuehneEllerhold** [comment]
@kartsims Could you please use a numeric version like 1.0 or something similar?

**Comment by kartsims** [comment]
Sorry for the late reply. A `1.0` tag has been pushed just now
