### ISSUE TITLE
Support Letter spacing

### ISSUE THREAD

**Issue by villanus** [kartsims/easysvg#3]
Provide option for letter spacing between characters

**Comment by villanus** [comment]
Looks like you can get this going by adding or subtracting an integer value from the following 2 lines:

 public function textDef($text)

``` PHP
            // next letter's position
            $horizAdvX += $this->font->glyphs[$letter]->horizAdvX * $fontSize +2;
```

And within function textDimensions($text)

``` PHP
            $lineWidth += $this->font->glyphs[$letter]->horizAdvX * $fontSize +2;
```

Can you please let me know how to set the default to 0, and how to pass in these values into the class?  Also it looks like if the value is positive, then the width needs to have one less tick so it wont leave an extra gap at the end. 

=)

**Comment by kartsims** [comment]
Thanks for creating this issue :)

Letters spacing is now supported since [this commit](https://github.com/kartsims/easysvg/commit/b1803b2786ec6c50e3e771e41ebc09162500e635). You may find usage examples in the README or in the `demo/index.php` file

**Comment by villanus** [comment]
Hello,
Thank you for the commit.  It works great except one tiny problem.
No Letter spacing should be added after the last character.
