### ISSUE TITLE
Port Tree Diagram to EasySvg? 

### ISSUE THREAD

**Issue by mattpaz** [kartsims/easysvg#30]
Not sure if anyone would be interested in doing this or not, but I thought someone _might_ have some appetite for doing something like this with easysvg. 

https://github.com/jimblackler/treefun
http://jimblackler.net/blog/?p=365
http://jimblackler.net/treefun/

It could prove an interesting set of sample code -- and an add-on utility that folks might leverage.

**Comment by kartsims** [comment]
Hi! Thanks for the suggestion but this is out of scope of this library that intends to generate SVG paths from SVG fonts, so rather focused on text manipulation. 

I am afraid tree diagrams should be the subject of a specific library.
