### ISSUE TITLE
Space characters lead to fatal errors

### ISSUE THREAD

**Issue by ginsterbusch** [kartsims/easysvg#33]
Fatal error: EasySVG->defScale(NULL, 0.048828125, -0.048828125)
So probably missing glyph. A workaround would be - if I knew - to just look for unicode 32 or 13, and then just add a manual spacing.
If I knew how, I'd probably add this myself, too :D

cu, w0lf.

**Comment by ginsterbusch** [comment]
Workaround for now:

Added right after line break support in method TextDef:

~~~
 if( $letter === 13 || $letter === 32 || empty( $this->font->glyphs[$letter]->d ) === true ) { // space chars
				// use _ instead, but display .. uhm .. nothing?
				
				 //$horizAdvX += $this->font->lineWidth * ($this->font->ascent + $this->font->descent);
				 $horizAdvX += ( $this->font->glyphs[$letter]->horizAdvX * $fontSize + $this->font->em * $this->font->letterSpacing * $fontSize * 1.5 );
				 continue;
			}
~~~

**Comment by ricardoboss** [comment]
Take a look at the function signature: https://github.com/kartsims/easysvg/blob/master/src/EasySVG.php#L462

If you are calling `defScale` manually, make sure you don't pass `null` into the first parameter. It only accepts variables of type `string`.

**Comment by ginsterbusch** [comment]
> If you are calling defScale manually, make sure you don't pass null into the first parameter. It only accepts variables of type string.

I DO NOT call it manually. It happens when adding text strings (with `addText`) that includes spaces. And that happens, because "empty" text is, out of some reason, not properly detected. I've checked multiple times - glyph exists. Might be an internal issue with UTF8. But the work-around certainly works, so, for now, all is cool (at least for me; YMMV).

**Comment by rac2030** [comment]
I just tried out the demo (pulled the package with composer) and I got the exception:
`FastCGI: server "/var/run/hcgi/102193" stderr: PHP Fatal error:  Uncaught TypeError: EasySVG::defScale(): Argument #1 ($def) must be of type string, null given`
When hitting /vendor/kartsims/easysvg/demo/
Quick test replacing the string in the demo with just "test" does not throw an error and demo works.

**Comment by rac2030** [comment]
Using my own font actually works, it just does not do a space so it seems have to do something with the example svg font that the space character breaks script execution with a fatal error

**Comment by rac2030** [comment]
I'm using fontforge to generate the SVG font and it seems if there are no points to draw for the character it's producing a glyph tag without the d attribute and this seems to break.
`<glyph glyph-name="space" unicode=" " horiz-adv-x="200" d="" />`
just by adding a d="" to the glyph tag fixes the issue.
All it needs is a null check to handle if d is not set ;-)
Will make a PR

**Comment by raphaelbastide** [comment]
I had the same problem and the fix didn’t change it, I fixed it by adding:

```
  // handle if d attribute is not set in corresponding glyph
  if(is_null($d)) {
    $d = "";
  }
```
after the line [315](https://github.com/kartsims/easysvg/blob/master/src/EasySVG.php#L315).

**Comment by ricardoboss** [comment]
@rac2030 Can you copy your fallback to after line 315? This should cover both yours and @raphaelbastide's problems.

**Comment by adrianschenker** [comment]
I made it work by adding "(string)" on line 315 in EasySVG.php:

Instead of:
`// extract character definition`
`$d = $this->font->glyphs[$letter]->d;`

This:
`// extract character definition`
`$d = (string) $this->font->glyphs[$letter]->d;`

**Comment by greendrake** [comment]
> I made it work by adding "(string)" on line 315 in EasySVG.php:

Works for me. Thanks!
