### ISSUE TITLE
SVG size to match SVG content

### ISSUE THREAD

**Issue by raphaelbastide** [kartsims/easysvg#35]
I wonder if there is a way to resize the SVG  to match its content only. Right now I have a difference between the height of the SVG tag, and the height of the path within this SVG: 

![svg](https://user-images.githubusercontent.com/193122/206173777-69477212-cc7f-4bd4-a19e-ec4d410bad71.png)

The font in this example is transformed in a single path, not embed font.

My php code:

	$svg = new EasySVG();
	$svg->setFontSVG($svgFont->filename);
	$svg->setFontSize(100);
	$svg->setFontColor('#000000');
	$svg->setLineHeight(0);
	$svg->setUseKerning(true);
	$svg->addText($demoText);
	list($textWidth, $textHeight) = $svg->textDimensions($demoText);
	$svg->addAttribute("viewbox", "0 0 $textWidth $textHeight");
	$svg->addAttribute("width", $textWidth."px");
	$svg->addAttribute("height", $textHeight."px");
	$svg->addAttribute("preserveAspectRatio","none");

Could be related to #23

**Comment by mia-riezebos** [comment]
I wonder if the viewbox 0,0 is so much higher than the text, is because there’s an ascender height that isn’t present on the paths in the svg, but still included in the textHeight calculation…

surely one would be able to gather the lowest (and highest) x&y values of all the paths in the svg, and then trim the viewbox to these values… sadly idk about any libraries or straight up ways to do this, just thinking along…

**Comment by mia-riezebos** [comment]
Apparently theres an inherent bounding box prop on an SVGGraphicsElement which you might set the viewbox to using js…

https://stackoverflow.com/a/29004579

and another possibly helpful stackoverflow entry:
https://stackoverflow.com/questions/16344288/calculating-svg-bounding-box-using-php-with-respect-to-curves

**Comment by raphaelbastide** [comment]
Thank you @mia-cx I will take a look at it!

**Comment by raphaelbastide** [comment]
I placed a [bounty](https://app.bountysource.com/issues/117992590-svg-size-to-match-svg-content) for that issue.

**Comment by mia-riezebos** [comment]
Still wanting to look into this but bigger, tighter deadlined projects came up first

**Comment by kartsims** [comment]
You want this to happen on the server side or in a browser window works for you?

I can see how to do that in JS but PHP is going to be harder.

**Comment by raphaelbastide** [comment]
> You want this to happen on the server side or in a browser window works for you?

Server side, ideally.

**Comment by partoa** [comment]
Is it acceptable if it uses a headless browser or node on the server side?

**Comment by raphaelbastide** [comment]
> Is it acceptable if it uses a headless browser or node on the server side?

EasySVG being a PHP library, that would be better to keep the solution to this precise problem PHP only, I suppose.

**Comment by partoa** [comment]
OK. Fair enough. I'd like to test with the font you're using. Are you able to share that?

**Comment by raphaelbastide** [comment]
Sure, you can have it [here](https://gitlab.com/raphaelbastide/Terminal-Grotesque) but the issue happens with all kind of fonts.

**Comment by partoa** [comment]
There is actually a bug with the demo, where the SVG d value is null... I'll just work around it for now. I noticed that is for the Unicode character 32. That's space.

**Comment by partoa** [comment]
I'll give this a go and see if I can come up with something.

**Comment by dojorno** [comment]
check out my solution https://github.com/dojorno/Bounties/blob/main/svgsizematch

**Comment by partoa** [comment]
@raphaelbastide Is this still open? I think I have a solution that I could implement if need be.

**Comment by raphaelbastide** [comment]
> @raphaelbastide Is this still open? I think I have a solution that I could implement if need be.

It is! Would you want me to test things before you push anything?

**Comment by partoa** [comment]
I definitely would. Will let you know when I'm ready.

**Comment by partoa** [comment]
I've done a bit of testing and research. Including testing with existing js libraries for calculating the bounding box:
https://github.com/icons8/svg-bounding-box
https://www.npmjs.com/package/svg-path-bbox
https://www.npmjs.com/package/svg-path-bounding-box

Nothing comes close to what the browser does. [https://stackoverflow.com/a/29004579](https://stackoverflow.com/a/29004579) shared by @mia-cx . As such, the most logical solution is executing js code in the backend. I can create a PHP utility if that is OK with you. Please let me know. Making a bounding box calculator for PHP from scratch, that behaves exactly as it should would take quite a bit of time.

**Comment by partoa** [comment]
@raphaelbastide I finally found the perfect solution. I believe I have solved the issue. It uses InkScape, and you'd have to have it installed for it to work.

Check out this branch on my repo. https://github.com/partoa/easysvg/tree/resize_svg_to_fit_path

I will now open a Pull Request.

**Comment by raphaelbastide** [comment]
@partoa I am going to try your solution. But if I have Inkscape installed on the server, I would not need EasySVG at all. Do you think no solution exist with PHP only?

**Comment by partoa** [comment]
A solution written in PHP, I doubt.

**Comment by partoa** [comment]
@raphaelbastide I take it using Inkscape is out of the question.

**Comment by raphaelbastide** [comment]
Using inkscape doesn’t solve the issue, indeed.

**Comment by kartsims** [comment]
@raphaelbastide let's have a chat on Discord `kartsims#7647` about this issue I believe the scope can be refined or tightened to make it more approachable

**Comment by partoa** [comment]
I'm there partoa

**Comment by millersartin** [comment]
To resize the SVG to match its content, you can adjust the viewBox attribute and make sure that the SVG container is only as large as the content inside it. Based on your code, it seems that you have already calculated the text width and height using the textDimensions function. Here's a modified version of your code that might help you achieve the desired result:


```
$svg = new EasySVG();
$svg->setFontSVG($svgFont->filename);
$svg->setFontSize(100);
$svg->setFontColor('#000000');
$svg->setLineHeight(0);
$svg->setUseKerning(true);
$svg->addText($demoText);
list($textWidth, $textHeight) = $svg->textDimensions($demoText);

// Get the current dimensions of the SVG container
$svgWidth = $svg->getAttribute("width");
$svgHeight = $svg->getAttribute("height");

// Calculate the new viewBox values based on the text dimensions
$newViewBoxWidth = min($textWidth, $svgWidth);
$newViewBoxHeight = min($textHeight, $svgHeight);

$svg->addAttribute("viewBox", "0 0 $newViewBoxWidth $newViewBoxHeight");
$svg->addAttribute("width", $newViewBoxWidth."px");
$svg->addAttribute("height", $newViewBoxHeight."px");
$svg->addAttribute("preserveAspectRatio", "none");
```

This should ensure that the SVG container is resized to match the content (path) inside it. However, if this still doesn't work, you may want to examine the SVG content generated by EasySVG and manually adjust the viewBox and dimensions to fit the content correctly

**Comment by raphaelbastide** [comment]
Considering solving this issue with PHP, within the library seam more difficult than I expeceted, I will close this issue  as wontfix and the likend bounty. I might go for a solution with JS, either server or client side.

**Comment by stefanfisk** [comment]
This can be done by using https://github.com/meyfa/php-svg.

```php
<?php

use EasySVG;
use SVG\Nodes\Shapes\SVGPath;
use SVG\Rasterization\Path\PathApproximator;
use SVG\Rasterization\Path\PathParser;
use SVG\Rasterization\Transform\Transform;
use SVG\SVG;

use function implode;
use function max;
use function min;

use const PHP_FLOAT_MAX;
use const PHP_FLOAT_MIN;

$text = "Simple text display\netc.";

$svg = new EasySVG();
$svg->setFont('om_telolet_om-webfont.svg', 100, '#000000');
$svg->setFontSize(24);
$svg->addText($text);

$svg = SVG::fromString($svg->asXML());

$xMin = PHP_FLOAT_MAX;
$xMax = PHP_FLOAT_MIN;
$yMin = PHP_FLOAT_MAX;
$yMax = PHP_FLOAT_MIN;

$pathParser       = new PathParser();
$pathApproximator = new PathApproximator(Transform::identity());

for ($i = 0; $i < $svg->getDocument()->countChildren(); $i++) {
    $child = $svg->getDocument()->getChild($i);

    if (! $child instanceof SVGPath) {
        continue;
    }

    $commands = $pathParser->parse($child->getDescription());
    $pathApproximator->approximate($commands);

    foreach ($pathApproximator->getSubpaths() as $subpath) {
        foreach ($subpath as $point) {
            $xMin = min($xMin, $point[0]);
            $xMax = max($xMax, $point[0]);
            $yMin = min($yMin, $point[1]);
            $yMax = max($yMax, $point[1]);
        }
    }
}

$width  = $xMax - $xMin;
$height = $yMax - $yMin;

$svg->getDocument()->setAttribute('width', $width);
$svg->getDocument()->setAttribute('height', $height);
$svg->getDocument()->setAttribute('viewBox', implode(' ', [$xMin, $yMin, $width, $height]));

echo $svg;

**Comment by kartsims** [comment]
great proposal @stefanfisk thanks!
