### ISSUE TITLE
Custom class names or ids for paths

### ISSUE THREAD

**Issue by villanus** [kartsims/easysvg#4]
Provide ability to inject custom ID or class to each line of text (path)

For example it would be nice to create an id for the SVG #myfirstsvg
and then each path have an id #line-1  #line-2 #line-3 

This would allow better flexibility when working with the SVG using Javascript

**Comment by villanus** [comment]
Looks like its available for the SVG itself with:
      $svg2->addAttribute("id", "weasel");

But is there a way to add a class or id to the paths?

**Comment by kartsims** [comment]
This feature is actually already available. Please take some time to read the doc ;-)

see https://gist.github.com/kartsims/34b5e07d95160fe1e2ec
