### ISSUE TITLE
Curved Text possible?

### ISSUE THREAD

**Issue by thimo1** [kartsims/easysvg#8]
I'd kindly ask if there's an easy way to create curved/bended text like arc 4%?

**Comment by kartsims** [comment]
Wow that's a tricky one !

Given the way the library works, this would require serious math skills ! I am not up to this challenge but we'll keep this issue open for a while just in case someone has an idea...

**Comment by amirgee007** [comment]
sir need help

**Comment by amirgee007** [comment]
![image](https://cloud.githubusercontent.com/assets/16411441/20298662/eb934074-ab38-11e6-8c2e-5c542e52673d.png)

sir when ever i used arial font SVG file or any other it gives me eror message like this in this line.
  $d = $this->font->glyphs[$letter]->d;

unable to understand the error. 
 ErrorException in EasySVG.php line 231:
Undefined offset: 13

**Comment by kartsims** [comment]
@amirgee007 please open your own issue and post a gist or code sample that I can test on my machine

**Comment by amirgee007** [comment]
issue solved there was problem in SVG font file.

thanks for your time and replly.
